# -*- coding: utf-8 -*-
"""diamond price predicter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPDiREHjFXjLXtoSSaWNUt0CwwFLqaLe
"""

import joblib

model = joblib.load('/content/drive/MyDrive/diamond_price.joblib')

carat = 0.91   # up to 5
cut = 1     # between 1 and 5
color = 2   # between 1 and 7
clarity = 6 # between 1 and 8

data_for_prediction = [[carat, cut, color, clarity]]
predictions = model.predict(data_for_prediction)
print(predictions[0])